server:
  port: 7001
spring:
  application:
    name: registry
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    fetch-registry: false         #false表示自己是注册中心，不需要检索服务
    register-with-eureka: false   #false表示不会注册自己
  server:
    enable-self-preservation: false #禁用自我保护