server:
  port: 7001
spring:
  application:
    name: registry
  profiles: eureka-1
eureka:
  instance:
    hostname: eureka-1
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
    fetch-registry: false         #false表示自己是注册中心，不需要检索服务
    register-with-eureka: false   #false表示不会注册自己
  server:
    enable-self-preservation: false #禁用自我保护
---
server:
  port: 7002
spring:
  application:
    name: registry
  profiles: eureka-2
eureka:
  instance:
    hostname: eureka-2
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    fetch-registry: false         #false表示自己是注册中心，不需要检索服务
  server:
    enable-self-preservation: false #禁用自我保护