server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: dept-provider
  profiles: dept-1
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka
  instance:
    prefer-ip-address: true  #显示ip
    instance-id: consumer-dept-8001  #服务名称
info:
  app.name: atguigu-microservicecloud
  company.name: www.wyu.com
  build.artifactId: microservice-provider-dept-8001
  build.version: 1.0.0-SNAPSHOT
---
server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: dept-provider
  profiles: dept-2
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka
  instance:
    prefer-ip-address: true  #显示ip
    instance-id: consumer-dept-8002  #服务名称
info:
  app.name: atguigu-microservicecloud
  company.name: www.wyu.com
  build.artifactId: microservice-provider-dept-8001
  build.version: 1.0.0-SNAPSHOT